### ISSUE TITLE
04 - Solution Strategy

### ISSUE THREAD

**Issue by fernandossmm** [Arquisoft/viade_en2b#13]

**Comment by UO264345** [comment]
Create branch `feature_arc42_04solution-strategy`.

**Comment by UO264345** [comment]
First commit: 8104dd2833bc83ee726752ec3320cdd092e9d6c8.

**Comment by UO264345** [comment]
Second commit: 4887fda185806fc2b057da4bec286f86db703bf0. The main points are tackled, but as said in the commit message, this commit is **not final**.

**Comment by UO264345** [comment]
First draft: db9fe5e4fb32a311048776f33205e1c3dcd9d225.
