### ISSUE TITLE
05 - Building Block View

### ISSUE THREAD

**Issue by fernandossmm** [Arquisoft/viade_en2b#14]

**Comment by UO264345** [comment]
Added the building block view diagram: d45f8ac5f47becf4394e5474c4964b2a86d36cbe.
This diagram will eventually grow and change, this is only what is envisioned by the team.

**Comment by UO264345** [comment]
Two first levels documented: 2b1fb201f99dc74f36347b803f0c422bf66b3122.

**Comment by UO264345** [comment]
First draft: 219ee64c2dd961c46202acc61fb19ec40454d3df.

**Comment by UO264345** [comment]
#35
