### ISSUE TITLE
09 - Design Decisions

### ISSUE THREAD

**Issue by fernandossmm** [Arquisoft/viade_en2b#18]
## 09 - Design Decisions

Design Decisions part of the documentatin draft.

### Parts of the document to be done

* [x] Brief Introduction
* [x] Architectural Decisions
* [x] Diagrams or Table with decisions taken 

#### Linked branch

* [Branch 09 Design Decissions] (https://github.com/Arquisoft/viade_en2b/tree/feature_arc42_09design_decissions)

#### Pull Requests Link
* [Pull Request Branch 09 Design Decissions](https://github.com/Arquisoft/viade_en2b/pull/32)

**Comment by guillefun** [comment]
Brief Introduction done.
