### ISSUE TITLE
Cucumber tests not starting

### ISSUE THREAD

**Issue by UO264345** [Arquisoft/viade_en2b#195]
## Bug description

Cucumber tests running in the browser end up in a timeout due to the application not starting fast enough. As of now, it is not known if the problem is the application taking too much time to start, the default timeout of Jest's configuration, or a badly implemented test.

### Files related with the problem (branch [e2e_login](https://github.com/Arquisoft/viade_en2b/tree/e2e_login))

- Puppeteer configuration: jest-puppeteer.config.js
- Jest configuration: e2e/jest-config.js
- Login feature: e2e/features/login.feature
- Login feature steps: e2e/step-definitions/login.steps.js

**Comment by pglez82** [comment]
I have solved the timeout. Now you have to fix the test. The solution is in this commit eb5dc88. 

I found the solution [here](https://stackoverflow.com/questions/49603939/async-callback-was-not-invoked-within-the-5000ms-timeout-specified-by-jest-setti)

The exact error message was in the console when launching the tests. Let me know if it works for you.

**Comment by UO264345** [comment]
Thank you very much. I also had to add another timeout because a `Navigation Timeout error` was being raised, but the tests are now running.

**Comment by pglez82** [comment]
Great! I am glad that its solved. Just one extra thing. I am linking to an [issue](https://github.com/Arquisoft/viade_en2a/issues/184#issuecomment-620465307) in group en2a that can help you debug your e2e tests. I didn't want to write this here again.

**Comment by UO264345** [comment]
Sure, thank you!
