### ISSUE TITLE
Update documentation (v1.0)

### ISSUE THREAD

**Issue by UO264345** [Arquisoft/viade_en2b#97]
## Feature description

Updating of the most relevant points of the documentation to date with the first deliverable, taking into account the current status of the development.

**Other development information, extensions and problems**: `none`

### Update

*   [x] Point 1. Introduction and goals.
*   [x] Point 2. Architecture constraints.
*   [x] Point 3. System scope and context.
*   [x] Point 4. Solution strategy.
*   [x] Point 5. Building block view.
*   [x] Point 6. Runtime view.
*   [x] Point 7. Deployment view.
*   [x] Point 8. Concepts.
*   [x] Point 9. Design decisions.
*   [x] Point 10. Quality scenarios.
*   [x] Point 11. Technical risks.
*   [x] Point 12. Glossary.

**Comment by guillefun** [comment]
[Issue: Update Design Decisions](https://github.com/Arquisoft/viade_en2b/issues/102)

**Comment by UO264345** [comment]
Point 7 left to next version of the project
